# Generated by Django 4.1.3 on 2022-11-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookreview_created_at_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='author_image',
            field=models.ImageField(default='default_author.png', upload_to=''),
        ),
    ]
