# Generated by Django 4.1.3 on 2022-11-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
