# Generated by Django 4.1.3 on 2022-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_moto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='moto',
        ),
        migrations.AddField(
            model_name='book',
            name='motto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
