# Generated by Django 4.1.3 on 2022-11-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_moto_book_motto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='motto',
        ),
        migrations.AddField(
            model_name='author',
            name='motto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
