# Generated by Django 4.1.3 on 2022-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_motto_author_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='author',
            name='motto',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='residency',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
